/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dialog;

import component.ThemeColor;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import form.Koneksi;
/**
 *
 * @author marwa
 */
public class EditPelangganDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(EditPelangganDialog.class.getName());

    /**
     * Creates new form TambahPelangganDialog
     */
    
    private int idPelanggan;
    
    public EditPelangganDialog(java.awt.Frame parent, boolean modal, int idPelanggan) {
        super(parent, modal);
        this.idPelanggan = idPelanggan;

        
        initComponents();
        mainPanel.setRadius(20);
        mainPanel.setBackground(ThemeColor.BACKGROUND);
        
        labelJudul.setForeground(ThemeColor.TEXT);
        
        btnBatal.setOutlineVariant();
        
        //placeholder
        namaField.setPreferredSize(new java.awt.Dimension(250, 40));
        namaField.setHint("Nama Pelanggan");
        
        noHPField.setPreferredSize(new java.awt.Dimension(250, 40));
        noHPField.setHint("08xx-xxxx-xxxx");
        
        // load data existing ke field
        loadDataPelanggan();
    }
    
    private void loadDataPelanggan() {
    try {
        Connection conn = Koneksi.getKoneksi();
        PreparedStatement ps = conn.prepareStatement(
            "SELECT nama, no_hp FROM pelanggan WHERE id = ?"
        );
        ps.setInt(1, idPelanggan);
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            namaField.setText(rs.getString("nama"));
            noHPField.setText(rs.getString("no_hp"));
        }

        rs.close();
        ps.close();

        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Gagal load data: " + e.getMessage(),
                "Error",
                javax.swing.JOptionPane.ERROR_MESSAGE
            );
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new component.RoundedPanel();
        labelJudul = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelNama1 = new javax.swing.JLabel();
        namaField = new component.ModernTextField();
        noHPField = new component.ModernTextField();
        btnSimpanEdit = new component.ModernButton();
        btnBatal = new component.ModernButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Edit Pelanggan");
        setResizable(false);

        labelJudul.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        labelJudul.setText("Edit Pelanggan");

        labelNama.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelNama.setText("Nama Lengkap*");

        labelNama1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelNama1.setText("No. HP*");

        btnSimpanEdit.setText("Simpan");
        btnSimpanEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanEditMouseClicked(evt);
            }
        });
        btnSimpanEdit.addActionListener(this::btnSimpanEditActionPerformed);

        btnBatal.setText("Batal");
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNama)
                    .addComponent(labelJudul, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainPanelLayout.createSequentialGroup()
                        .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSimpanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noHPField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(namaField, javax.swing.GroupLayout.DEFAULT_SIZE, 389, Short.MAX_VALUE))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelJudul)
                .addGap(18, 18, 18)
                .addComponent(labelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(labelNama1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noHPField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpanEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanEditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanEditMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanEditMouseClicked

    private void btnSimpanEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanEditActionPerformed
    String nama = namaField.getText().trim();
    String noHp = noHPField.getText().trim();

    if (nama.isEmpty() || noHp.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Nama dan No. HP wajib diisi!",
            "Peringatan",
            javax.swing.JOptionPane.WARNING_MESSAGE
        );
        return;
    }

    try {
        Connection conn = Koneksi.getKoneksi();
        PreparedStatement ps = conn.prepareStatement(
            "UPDATE pelanggan SET nama = ?, no_hp = ? WHERE id = ?"
        );
        ps.setString(1, nama);
        ps.setString(2, noHp);
        ps.setInt(3, idPelanggan);
        ps.executeUpdate();

        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Pelanggan berhasil diperbarui!",
            "Sukses",
            javax.swing.JOptionPane.INFORMATION_MESSAGE
        );

        dispose();

    } catch (SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(
            this,
            "Gagal memperbarui: " + e.getMessage(),
            "Error",
            javax.swing.JOptionPane.ERROR_MESSAGE
        );
    }
    }//GEN-LAST:event_btnSimpanEditActionPerformed

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.ModernButton btnBatal;
    private component.ModernButton btnSimpanEdit;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNama1;
    private component.RoundedPanel mainPanel;
    private component.ModernTextField namaField;
    private component.ModernTextField noHPField;
    // End of variables declaration//GEN-END:variables
}
