/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package dialog;

import component.ThemeColor;
import javax.swing.JOptionPane;
import javax.swing.border.AbstractBorder;
import java.awt.*;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import form.Koneksi;
/**
 *
 * @author rhmnsae
 */
public class TambahItemDialog extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TambahItemDialog.class.getName());
    
    /**
     * Creates new form TambahPelangganDialog
     */
    public TambahItemDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        mainPanel.setRadius(20);
        mainPanel.setBackground(ThemeColor.BACKGROUND);
        
        labelJudul.setForeground(ThemeColor.TEXT);
        
        btnBatal.setOutlineVariant();
        
        //placeholder
        namaField.setHint("Contoh: Facial Brightening");
        hargaField.setHint("Contoh: 50000");
        durasiField.setHint("Contoh: 60");
        deskripsiField.setHint("Tambahkan deskripsi item");
        
        updateDurasiLabel();

        jComboBoxTipe.addActionListener(e -> updateDurasiLabel());
        
        styleComboBox(jComboBoxTipe);
        styleComboBox(jComboBoxStatus);
    }
    
    
    private void updateDurasiLabel() {

        String tipe = jComboBoxTipe.getSelectedItem().toString();

        if (tipe.equals("Produk (Barang)")) {

            labelNama3.setText("Stok Awal*");
            durasiField.setHint("Contoh: 10");

        } else {

            labelNama3.setText("Durasi (menit)*");
            durasiField.setHint("Contoh: 60");
        }
    
    }
    
    class RoundedBorder extends AbstractBorder {

        private final int radius;

        RoundedBorder(int radius) {
            this.radius = radius;
        }

        @Override
        public void paintBorder(Component c, Graphics g,
                int x, int y, int width, int height) {

            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(
                    RenderingHints.KEY_ANTIALIASING,
                    RenderingHints.VALUE_ANTIALIAS_ON
            );

            g2.setColor(new Color(45, 45, 55));
            g2.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
        }

        @Override
        public Insets getBorderInsets(Component c) {
            return new Insets(8, 12, 8, 12);
        }

        @Override
        public Insets getBorderInsets(Component c, Insets insets) {
            insets.left = insets.right = 12;
            insets.top = insets.bottom = 8;
            return insets;
        }
    }
    
    private void styleComboBox(javax.swing.JComboBox<String> comboBox) {
                
        comboBox.setOpaque(false);

        comboBox.setBackground(new Color(30, 30, 36));
        comboBox.setForeground(Color.WHITE);

        comboBox.setFont(new Font("SansSerif", Font.PLAIN, 12));

        comboBox.setBorder(new RoundedBorder(20));

        comboBox.setFocusable(false);

        comboBox.setRenderer(new javax.swing.DefaultListCellRenderer() {

            @Override
            public Component getListCellRendererComponent(
                    javax.swing.JList<?> list,
                    Object value,
                    int index,
                    boolean isSelected,
                    boolean cellHasFocus) {

                Component c = super.getListCellRendererComponent(
                        list, value, index, isSelected, cellHasFocus);

                list.setBackground(new Color(30, 30, 36));
                list.setForeground(Color.WHITE);

                setBorder(javax.swing.BorderFactory.createEmptyBorder(
                        5, 10, 5, 10));

                return c;
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new component.RoundedPanel();
        labelJudul = new javax.swing.JLabel();
        labelNama = new javax.swing.JLabel();
        labelNama1 = new javax.swing.JLabel();
        namaField = new component.ModernTextField();
        btnSimpan = new component.ModernButton();
        btnBatal = new component.ModernButton();
        labelNama2 = new javax.swing.JLabel();
        hargaField = new component.ModernTextField();
        labelNama3 = new javax.swing.JLabel();
        durasiField = new component.ModernTextField();
        labelNama4 = new javax.swing.JLabel();
        deskripsiField = new component.ModernTextField();
        labelNama5 = new javax.swing.JLabel();
        jComboBoxStatus = new javax.swing.JComboBox<>();
        jComboBoxTipe = new javax.swing.JComboBox<>();
        labelNama6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Item");
        setResizable(false);

        labelJudul.setFont(new java.awt.Font("SansSerif", 1, 28)); // NOI18N
        labelJudul.setText("Tambah Item");

        labelNama.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelNama.setForeground(new java.awt.Color(240, 237, 232));
        labelNama.setText("Nama Item*");

        labelNama1.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelNama1.setForeground(new java.awt.Color(240, 237, 232));
        labelNama1.setText("Tipe*");

        namaField.addActionListener(this::namaFieldActionPerformed);

        btnSimpan.setText("Simpan");
        btnSimpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSimpanMouseClicked(evt);
            }
        });
        btnSimpan.addActionListener(this::btnSimpanActionPerformed);

        btnBatal.setText("Batal");
        btnBatal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBatalMouseClicked(evt);
            }
        });
        btnBatal.addActionListener(this::btnBatalActionPerformed);

        labelNama2.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelNama2.setForeground(new java.awt.Color(240, 237, 232));
        labelNama2.setText("Harga*");

        labelNama3.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelNama3.setForeground(new java.awt.Color(240, 237, 232));
        labelNama3.setText("Durasi (menit)*");

        labelNama4.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelNama4.setForeground(new java.awt.Color(240, 237, 232));
        labelNama4.setText("Deskripsi*");

        labelNama5.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelNama5.setText("Status*");

        jComboBoxStatus.setBackground(new java.awt.Color(30, 30, 36));
        jComboBoxStatus.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBoxStatus.setForeground(new java.awt.Color(240, 237, 232));
        jComboBoxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aktif", "Nonaktif" }));
        jComboBoxStatus.addActionListener(this::jComboBoxStatusActionPerformed);

        jComboBoxTipe.setBackground(new java.awt.Color(30, 30, 36));
        jComboBoxTipe.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        jComboBoxTipe.setForeground(new java.awt.Color(240, 237, 232));
        jComboBoxTipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Layanan (Jasa)", "Produk (Barang)" }));

        labelNama6.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        labelNama6.setForeground(new java.awt.Color(240, 237, 232));
        labelNama6.setText("Status*");

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelNama4)
                    .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(deskripsiField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelNama, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(labelJudul, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(mainPanelLayout.createSequentialGroup()
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNama1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(durasiField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelNama3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxTipe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelNama2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelNama5, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(labelNama6, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addComponent(namaField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelJudul)
                .addGap(18, 18, 18)
                .addComponent(labelNama)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(mainPanelLayout.createSequentialGroup()
                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(mainPanelLayout.createSequentialGroup()
                                .addComponent(namaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(labelNama1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(hargaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jComboBoxTipe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(mainPanelLayout.createSequentialGroup()
                                        .addComponent(labelNama2)
                                        .addGap(43, 43, 43))))
                            .addComponent(labelNama5))
                        .addGap(18, 18, 18)
                        .addComponent(labelNama3))
                    .addComponent(labelNama6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(durasiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(labelNama4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(deskripsiField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBatal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSimpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSimpanMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSimpanMouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String nama = namaField.getText().trim();
        String tipeUI
                = jComboBoxTipe.getSelectedItem().toString();
        String harga = hargaField.getText().trim();
        String inputDurasiStok
                = durasiField.getText().trim();
        String statusUI
                = jComboBoxStatus.getSelectedItem().toString();
        String deskripsi
                = deskripsiField.getText().trim();

        // validasi kosong
        if (nama.isEmpty()
                || harga.isEmpty()
                || inputDurasiStok.isEmpty()
                || deskripsi.isEmpty()) {

            JOptionPane.showMessageDialog(
                    this,
                    "Semua field wajib diisi!"
            );

            return;
        }

        try {

            Integer.parseInt(harga);
            Integer.parseInt(inputDurasiStok);

        } catch (NumberFormatException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Harga dan Durasi/Stok harus angka!"
            );

            return;
        }

        // mapping tipe
        String tipeDB;

        if (tipeUI.equals("Layanan (Jasa)")) {
            tipeDB = "service";
        } else {
            tipeDB = "product";
        }

        // mapping status
        String statusDB;

        if (statusUI.equals("Aktif")) {
            statusDB = "aktif";
        } else {
            statusDB = "non aktif";
        }

        String durasi = "-";
        int stok = 0;

        if (tipeDB.equals("service")) {

            durasi = inputDurasiStok + " menit";

        } else {

            stok = Integer.parseInt(inputDurasiStok);
        }

        try {

            Connection conn = Koneksi.getKoneksi();

            String sql = """
            INSERT INTO item
            (nama, tipe, harga, durasi, deskripsi, stok, status)
            VALUES (?, ?, ?, ?, ?, ?, ?)
            """;

            PreparedStatement ps
                    = conn.prepareStatement(sql);

            ps.setString(1, nama);
            ps.setString(2, tipeDB);
            ps.setInt(3, Integer.parseInt(harga));
            ps.setString(4, durasi);
            ps.setString(5, deskripsi);
            ps.setInt(6, stok);
            ps.setString(7, statusDB);

            ps.executeUpdate();

            JOptionPane.showMessageDialog(
                    this,
                    "Item berhasil ditambahkan!"
            );

            dispose();

        } catch (SQLException e) {

            JOptionPane.showMessageDialog(
                    this,
                    "Gagal menyimpan: " + e.getMessage()
            );
        }
    
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBatalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBatalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBatalMouseClicked

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void namaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaFieldActionPerformed

    private void jComboBoxStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxStatusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private component.ModernButton btnBatal;
    private component.ModernButton btnSimpan;
    private component.ModernTextField deskripsiField;
    private component.ModernTextField durasiField;
    private component.ModernTextField hargaField;
    private javax.swing.JComboBox<String> jComboBoxStatus;
    private javax.swing.JComboBox<String> jComboBoxTipe;
    private javax.swing.JLabel labelJudul;
    private javax.swing.JLabel labelNama;
    private javax.swing.JLabel labelNama1;
    private javax.swing.JLabel labelNama2;
    private javax.swing.JLabel labelNama3;
    private javax.swing.JLabel labelNama4;
    private javax.swing.JLabel labelNama5;
    private javax.swing.JLabel labelNama6;
    private component.RoundedPanel mainPanel;
    private component.ModernTextField namaField;
    // End of variables declaration//GEN-END:variables
}
