/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

/**
 *
 * @author asus_
 */
public class CardItem extends javax.swing.JPanel {

    /**
     * Creates new form CardItem
     */
    public CardItem() {
        initComponents();
        
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
    }
    
    public void setData(String nama, int harga, String tipe, String deskripsi, String durasiStok) {
        // 1. Set Nama dan Harga
        lblNamaItem.setText(nama);
        String formatHarga = String.format("%,d", harga).replace(',', '.');
        lblHarga.setText("Rp " + formatHarga);

        // 2. Set Deskripsi dan Durasi/Stok
        lblDeskripsiItem.setText(deskripsi);
        lblDurasiStok.setText(durasiStok);

        // 3. Set Teks Kategori
        // Asumsi data dari database adalah "Layanan" atau "Produk"
        lblKategori.setText(tipe.toUpperCase());

        // 4. Set Warna Berdasarkan Kategori
        if (tipe.equalsIgnoreCase("service")) {
            // Jika Layanan: Background Emas, Teks Hitam
            jPanel1.setBackground(new java.awt.Color(201, 168, 76)); 
            lblKategori.setForeground(new java.awt.Color(0, 0, 0));
            
            lblTipeDurasiStok.setText("Menit");
        } else if (tipe.equalsIgnoreCase("product")) {
            // Jika Produk: Background Biru/Abu-abu gelap (Silakan sesuaikan RGB-nya), Teks Putih
            jPanel1.setBackground(new java.awt.Color(64, 84, 115)); 
            lblKategori.setForeground(new java.awt.Color(255, 255, 255));
            
            lblTipeDurasiStok.setText("Stok");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblKategori = new javax.swing.JLabel();
        lblNamaItem = new javax.swing.JLabel();
        lblDeskripsiItem = new javax.swing.JLabel();
        lblHarga = new javax.swing.JLabel();
        lblDurasiStok = new javax.swing.JLabel();
        lblTipeDurasiStok = new javax.swing.JLabel();

        setBackground(new java.awt.Color(22, 22, 26));
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jPanel1.setBackground(new java.awt.Color(201, 168, 76));

        lblKategori.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblKategori.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblKategori.setText("KATEGORI");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(lblKategori)
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblKategori, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        lblNamaItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamaItem.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaItem.setText("Nama Item");

        lblDeskripsiItem.setForeground(new java.awt.Color(204, 204, 204));
        lblDeskripsiItem.setText("Deskripsi item");

        lblHarga.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblHarga.setForeground(new java.awt.Color(201, 168, 76));
        lblHarga.setText("Rp 0");

        lblDurasiStok.setForeground(new java.awt.Color(204, 204, 204));
        lblDurasiStok.setText("30");

        lblTipeDurasiStok.setForeground(new java.awt.Color(204, 204, 204));
        lblTipeDurasiStok.setText("Menit");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDurasiStok)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTipeDurasiStok))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNamaItem)
                    .addComponent(lblDeskripsiItem)
                    .addComponent(lblHarga))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNamaItem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDeskripsiItem)
                .addGap(41, 41, 41)
                .addComponent(lblHarga)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDurasiStok)
                    .addComponent(lblTipeDurasiStok))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDeskripsiItem;
    private javax.swing.JLabel lblDurasiStok;
    private javax.swing.JLabel lblHarga;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JLabel lblNamaItem;
    private javax.swing.JLabel lblTipeDurasiStok;
    // End of variables declaration//GEN-END:variables
}
