/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

/**
 *
 * @author asus_
 */
public class CartItem extends javax.swing.JPanel {

    /**
     * Creates new form CartItem
     */
    public CartItem() {
        initComponents();
        
        btnTambahQty.setMargin(new java.awt.Insets(0, 0, 0, 0));
        btnKurangQty.setMargin(new java.awt.Insets(0, 0, 0, 0));
    }
    
    public void setData(String nama, int harga, int qty) {
        // 1. Set Nama Item
        lblNamaItem.setText(nama);
        
        // 2. Set Harga Satuan
        String formatHarga = String.format("%,d", harga).replace(',', '.');
        lblHargaSatuan.setText("Rp " + formatHarga);
        
        // 3. Set Qty
        lblQtyItem.setText(String.valueOf(qty));
        lblQty.setText(String.valueOf(qty));
        
        // 4. Hitung dan Set Total Harga per Item (Harga * Qty)
        int totalHargaItem = harga * qty;
        String formatTotal = String.format("%,d", totalHargaItem).replace(',', '.');
        lblTotalHarga.setText("Rp " + formatTotal);
    }

    public javax.swing.JButton getBtnTambah() {
        return btnTambahQty;
    }

    public javax.swing.JButton getBtnKurang() {
        return btnKurangQty;
    }
    
    public javax.swing.JButton getBtnHapus() {
        return btnHapus;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamaItem = new javax.swing.JLabel();
        lblHargaSatuan = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblQtyItem = new javax.swing.JLabel();
        btnKurangQty = new javax.swing.JButton();
        btnTambahQty = new javax.swing.JButton();
        lblQty = new javax.swing.JLabel();
        lblTotalHarga = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();

        setBackground(new java.awt.Color(22, 22, 26));

        lblNamaItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblNamaItem.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaItem.setText("Nama item");

        lblHargaSatuan.setForeground(new java.awt.Color(204, 204, 204));
        lblHargaSatuan.setText("Harga Satuan");

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("x");

        lblQtyItem.setForeground(new java.awt.Color(204, 204, 204));
        lblQtyItem.setText("qty");

        btnKurangQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnKurangQty.setText("-");
        btnKurangQty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKurangQty.addActionListener(this::btnKurangQtyActionPerformed);

        btnTambahQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnTambahQty.setText("+");
        btnTambahQty.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTambahQty.addActionListener(this::btnTambahQtyActionPerformed);

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblQty.setForeground(new java.awt.Color(255, 255, 255));
        lblQty.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblQty.setText("1");

        lblTotalHarga.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblTotalHarga.setForeground(new java.awt.Color(201, 168, 76));
        lblTotalHarga.setText("Total Harga");

        btnHapus.setBackground(new java.awt.Color(255, 51, 51));
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("Hapus");
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnKurangQty)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambahQty))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblHargaSatuan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblQtyItem))
                    .addComponent(lblNamaItem, javax.swing.GroupLayout.DEFAULT_SIZE, 203, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTotalHarga, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaItem, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(lblTotalHarga))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(lblQtyItem))
                    .addComponent(lblHargaSatuan))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnKurangQty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnTambahQty, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblQty, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(btnHapus, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnKurangQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKurangQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnKurangQtyActionPerformed

    private void btnTambahQtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahQtyActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnTambahQtyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnKurangQty;
    private javax.swing.JButton btnTambahQty;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblHargaSatuan;
    private javax.swing.JLabel lblNamaItem;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblQtyItem;
    private javax.swing.JLabel lblTotalHarga;
    // End of variables declaration//GEN-END:variables
}
