/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package swing;

/**
 *
 * @author asus_
 */
public class MemberInCart extends javax.swing.JPanel {

    /**
     * Creates new form MemberInCart
     */
    public MemberInCart() {
        initComponents();
    }
    
    public void setData(String nama, int poin) {
        lblNamaMember.setText(nama);
        lblTotalPoin.setText(String.format("%,d", poin).replace(',', '.') + " poin");

        // Logika Penentuan Tier dan Diskon Kelipatan 3%
        String namaTier = "";
        int diskon = 0;
        int maxPoin = 0;
        java.awt.Color warnaBg = null;

        if (poin < 200) {
            namaTier = "Bronze"; diskon = 0; maxPoin = 200; 
            warnaBg = new java.awt.Color(205, 127, 50);
        } else if (poin < 500) {
            namaTier = "Silver"; diskon = 3; maxPoin = 500; 
            warnaBg = new java.awt.Color(192, 192, 192);
        } else if (poin < 1000) {
            namaTier = "Gold"; diskon = 6; maxPoin = 1000; 
            warnaBg = new java.awt.Color(255, 215, 0);
        } else if (poin < 2000) {
            namaTier = "Platinum"; diskon = 9; maxPoin = 2000; 
            warnaBg = new java.awt.Color(229, 228, 226);
        } else {
            namaTier = "Diamond"; diskon = 12; maxPoin = poin; // Poin maksimal dinamis
            warnaBg = new java.awt.Color(185, 242, 255);
        }

        lblTier.setText(namaTier);
        lblTier.setForeground(warnaBg); // Menyamakan warna teks tier dengan warna tiernya
        
        if (diskon > 0) {
            lblDiskon.setText("Diskon " + diskon + "% aktif");
            lblDiskon.setForeground(new java.awt.Color(76, 175, 130)); // Warna hijau jika ada diskon
        } else {
            lblDiskon.setText("Belum ada diskon");
            lblDiskon.setForeground(new java.awt.Color(204, 204, 204));
        }

        // --- Logika Progress Bar Tier ---
        double percent = (double) poin / maxPoin;
        if (percent > 1.0) percent = 1.0;
        int fillWidth = (int) (300 * percent); // Asumsi lebar maksimum panel adalah 300px

        PanelPersentaseTier.removeAll();
        PanelPersentaseTier.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT, 0, 0));
        
        javax.swing.JPanel barIsi = new javax.swing.JPanel();
        barIsi.setBackground(warnaBg);
        barIsi.setPreferredSize(new java.awt.Dimension(fillWidth, 4));
        
        PanelPersentaseTier.add(barIsi);
        PanelPersentaseTier.revalidate();
        PanelPersentaseTier.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNamaMember = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTier = new javax.swing.JLabel();
        lblTotalPoin = new javax.swing.JLabel();
        lblDiskon = new javax.swing.JLabel();
        PanelPersentaseTier = new javax.swing.JPanel();

        setBackground(new java.awt.Color(22, 22, 26));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        lblNamaMember.setForeground(new java.awt.Color(255, 255, 255));
        lblNamaMember.setText("Nama Member");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("|");

        lblTier.setForeground(new java.awt.Color(255, 255, 255));
        lblTier.setText("Tier");

        lblTotalPoin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblTotalPoin.setForeground(new java.awt.Color(201, 168, 76));
        lblTotalPoin.setText("Total Poin");

        lblDiskon.setForeground(new java.awt.Color(204, 204, 204));
        lblDiskon.setText("Diskon 3% aktif");

        javax.swing.GroupLayout PanelPersentaseTierLayout = new javax.swing.GroupLayout(PanelPersentaseTier);
        PanelPersentaseTier.setLayout(PanelPersentaseTierLayout);
        PanelPersentaseTierLayout.setHorizontalGroup(
            PanelPersentaseTierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        PanelPersentaseTierLayout.setVerticalGroup(
            PanelPersentaseTierLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDiskon)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(PanelPersentaseTier, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblNamaMember)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblTier)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                                .addComponent(lblTotalPoin)))
                        .addGap(21, 21, 21))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamaMember)
                    .addComponent(jLabel2)
                    .addComponent(lblTier)
                    .addComponent(lblTotalPoin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PanelPersentaseTier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblDiskon)
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelPersentaseTier;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblDiskon;
    private javax.swing.JLabel lblNamaMember;
    private javax.swing.JLabel lblTier;
    private javax.swing.JLabel lblTotalPoin;
    // End of variables declaration//GEN-END:variables
}
